---
driver:
  name: vagrant

provisioner:
  hosts: all
  name: ansible_playbook
  playbook: ./playbook.yml
  roles_path: ./
  # Use el7 epel repo instead of the default el6
  #ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
  #require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_repo: true
  ansible_version: latest
  ansible_verbosity: 2
  ansible_verbose: true
  require_windows_support: true
  # starting playbook is at: test/integration/default/default.yml

verifier:
  name: inspec

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2
    verifier:
      name: pester
      test_folder: test
  - name: windows-2016
    driver_config:
      box: mwrock/Windows2016
    verifier:
      name: pester
      test_folder: test

suites:
  - name: default


# https://thomascfoulds.com/2018/10/18/testing-ansible-roles-with-kitchen-inspec.html
# suites:
#   - name: default
#     provisioner:
#       playbook: scenarios/default/main.yml
#     verifier:
#       inspec_tests:
#         - path: scenarios/default/test.rb
