---
driver:
  name: vagrant

provisioner:
  hosts: all
  name: ansible_playbook
  playbook: ./playbook.yml
  roles_path: ./
  # Use el7 epel repo instead of the default el6
  #ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
  #require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_repo: true
  ansible_version: latest
  ansible_verbosity: 2
  ansible_verbose: true
  # starting playbook is at: test/integration/default/default.yml

verifier:
  name: inspec

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2
  - name: windows-2016
    driver_config:
      box: mwrock/Windows2016

suites:
  - name: default
