repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    #- id: no-commit-to-branch
    #  args: [--branch, master]
    - id: pretty-format-json
      args: [--autofix]
- repo: https://github.com/Yelp/detect-secrets
  rev: v0.14.3
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/tests/.*
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
    - id: script-must-have-extension
    - id: shfmt
    - id: shellcheck
    - id: forbid-binary
    - id: git-check  # Configure in .gitattributes
    - id: git-dirty  # Configure in .gitignore
      args: [-C, -e, SC1091, -e, SC2154]
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.7
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
