---

- name: Create directory structure
  win_file:
    path: "{{ deploy_folder }}"
    state: directory

- name: Create config scripts directory structure
  win_file:
    path: "{{ configuration_scripts_folder }}"
    state: directory
